/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Purchases_Create_Update = require('./code/before-purchases-create-update');
const on_Redemptions_Update = require('./code/on-redemptions-update');

class estudos_buildcode_java_1_cdsSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Purchases', async (request) => {
            await before_Purchases_Create_Update(request);
        });

        this.on('UPDATE', 'Redemptions', async (request, next) => {
            return on_Redemptions_Update(request, next);
        });

        return super.init();
    }
}


module.exports = {
    estudos_buildcode_java_1_cdsSrv
};